In [46]:
import numpy as np
import gymnasium as gym # pip intall gym
import random

In [55]:
env = gym.make('FrozenLake-v1', is_slippery = True)

In [56]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
qtable


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
#Hyper Parameters

total_episodes = 100000
learning_rate = 0.2 # 0-1
max_steps = 100
gamma = 0.8

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [59]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()[0]
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) #Exploit
        else:
            action = env.action_space.sample() #Explore
    
        temp = env.step(action)
        
        new_state = temp[0]
        reward = temp[1]
        done = temp[2]
        
        max_new_state = np.max(qtable[new_state,:])
        
        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        
        total_rewards += reward
        
        state = new_state
        if done:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
        
print("Score:", str(sum(rewards)/total_episodes))


KeyboardInterrupt: 

In [60]:
print(qtable)

[[0.00908662 0.01263066 0.00738416 0.00559855]
 [0.00486537 0.00618229 0.00745905 0.01267611]
 [0.0306222  0.00686082 0.00665012 0.00942786]
 [0.00519511 0.0045014  0.00523862 0.01011097]
 [0.02950319 0.01091538 0.00972642 0.00330165]
 [0.         0.         0.         0.        ]
 [0.01203108 0.0208426  0.05300861 0.00574779]
 [0.         0.         0.         0.        ]
 [0.01924685 0.02474101 0.00883663 0.06413594]
 [0.04709353 0.13166999 0.07078016 0.0362636 ]
 [0.18039115 0.05661708 0.03217944 0.05395237]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.09104093 0.09850945 0.13838709 0.08831618]
 [0.20853803 0.218948   0.21803217 0.45946072]
 [0.         0.         0.         0.        ]]


In [61]:
actions_=["LEFT","DOWN","RIGHT", "UP"]




for i in range(16):
    print(i,actions_[np.argmax(qtable[i,:])])

0 DOWN
1 UP
2 LEFT
3 UP
4 LEFT
5 LEFT
6 RIGHT
7 LEFT
8 UP
9 DOWN
10 LEFT
11 LEFT
12 LEFT
13 RIGHT
14 UP
15 LEFT


In [62]:
import time

In [63]:
env = gym.make('FrozenLake-v1', is_slippery = True, render_mode="human")



observation, info = env.reset()
step=0
done=0
new_state=0

while done == 0 and step<25:

    current_state_actions_array=qtable[new_state,:]
    print(current_state_actions_array)

    action= current_state_actions_array.argmax()

    temp = env.step(action)
    new_state = temp[0]
    done = temp[2]

    print(action)
    time.sleep(1)
    step=step+1

env.close()

[0.00908662 0.01263066 0.00738416 0.00559855]
1
[0.02950319 0.01091538 0.00972642 0.00330165]
0
[0.01924685 0.02474101 0.00883663 0.06413594]
3
[0.02950319 0.01091538 0.00972642 0.00330165]
0
[0.01924685 0.02474101 0.00883663 0.06413594]
3
[0.01924685 0.02474101 0.00883663 0.06413594]
3
[0.04709353 0.13166999 0.07078016 0.0362636 ]
1
[0.18039115 0.05661708 0.03217944 0.05395237]
0
[0.01203108 0.0208426  0.05300861 0.00574779]
2


In [35]:
qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])

In [34]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        env.render()
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

Episode: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps: 5
Episode: 2
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps: 5
Episode: 3
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps: 5
Episode: 4
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps: 5
Episode: 5
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF