In [17]:
import numpy as np
import gym # pip intall gym
import random

In [18]:
pip install gym

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
env = gym.make('FrozenLake-v1', is_slippery = True)

In [20]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
qtable


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#Hyper Parameters

total_episodes = 10000
learning_rate = 0.2 # 0-1
max_steps = 100
gamma = 0.8

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [22]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()[0]
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) #Exploit
        else:
            action = env.action_space.sample() #Explore
    
        temp = env.step(action)
        
        new_state = temp[0]
        reward = temp[1]
        done = temp[2]
        
        max_new_state = np.max(qtable[new_state,:])
        
        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        
        total_rewards += reward
        
        state = new_state
        if done:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
        
print("Score:", str(sum(rewards)/total_episodes))


Score: 0.2303


In [23]:
print(qtable)

[[0.00373948 0.00300461 0.01141294 0.00359313]
 [0.0032788  0.00334808 0.00301822 0.01062231]
 [0.00469419 0.01216637 0.0045998  0.00465034]
 [0.002998   0.0030386  0.0014864  0.00818072]
 [0.0186322  0.00713858 0.01417029 0.00575602]
 [0.         0.         0.         0.        ]
 [0.00401824 0.07234801 0.00576275 0.00585019]
 [0.         0.         0.         0.        ]
 [0.00744529 0.01095292 0.01117447 0.03017486]
 [0.04179768 0.12212858 0.03791453 0.04184608]
 [0.31980846 0.04135911 0.06255965 0.05046628]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.03303603 0.07546743 0.23209169 0.0795683 ]
 [0.23915507 0.22122132 0.62647052 0.20233655]
 [0.         0.         0.         0.        ]]


In [24]:
actions_=["LEFT","DOWN","RIGHT", "UP"]




for i in range(16):
    print(i,actions_[np.argmax(qtable[i,:])])

0 RIGHT
1 UP
2 DOWN
3 UP
4 LEFT
5 LEFT
6 DOWN
7 LEFT
8 UP
9 DOWN
10 LEFT
11 LEFT
12 LEFT
13 RIGHT
14 RIGHT
15 LEFT


In [25]:
import time
!pip install pygame


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
env = gym.make('FrozenLake-v1', is_slippery = False, render_mode="human")



observation, info = env.reset()
step=0
done=0
new_state=0

while done == 0 and step<25:

    current_state_actions_array=qtable[new_state,:]
    print(current_state_actions_array)

    action= current_state_actions_array.argmax()

    temp = env.step(action)
    new_state = temp[0]
    done = temp[2]

    print(action)
    time.sleep(1)
    step=step+1

env.close()

[0.00373948 0.00300461 0.01141294 0.00359313]
2
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.01062231]
3
[0.0032788  0.00334808 0.00301822 0.0106

In [27]:
qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])

In [28]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        env.render()
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

error: display Surface quit